name: ardumont
trace: false
safe: true
pygments: true
markdown: redcarpet

encoding: utf-8

redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
