# Site settings
name: ardumont
job: developer/devops
title: "tony's blog"
email: eniotna.t[at]gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My notes and articles for the world to enjoy.

baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://ardumont.github.io" # the base hostname & protocol for your site
author: "@ardumont"
twitter_username: ardumont
github_username:  ardumont

trace: false
safe: true
highlighter: pygments

encoding: utf-8

# Build settings
#markdown: kramdown
markdown: redcarpet
# redcarpet:
#   extensions: [ "no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
